apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-zabbix-mqtt-forwarder-dep
  labels:
    app: ttn-zabbix-mqtt-forwarder
    app.kubernetes.io/name: ttn-zabbix-mqtt-forwarder
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttn-zabbix-mqtt-forwarder
  template:
    metadata:
      labels:
        app: ttn-zabbix-mqtt-forwarder
    spec:
      imagePullSecrets:
      - name: hub-opendba.lv

      containers:
      - name: ttn-zabbix-mqtt-forwarder
        image: {{ .Values.imageName }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add: []
          runAsUser: 20000
        resources:
          limits:
            memory: 128M
            cpu: 100m
          requests:
            memory: 128M
            cpu: 100m
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: DEBUG
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: LOG_FORMAT
        - name: LOG_PERSIST
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: LOG_PERSIST
        - name: ZBX_HOST
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: ZBX_HOST
        - name: ZBX_PORT
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: ZBX_PORT
        - name: MQTT_HOST
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: MQTT_HOST
        - name: MQTT_PORT
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: MQTT_PORT
        - name: MQTT_TLS
          valueFrom:
            configMapKeyRef:
              name: ttn-zabbix-mqtt-forwarder-configmap
              key: MQTT_TLS
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ttn-zabbix-mqtt-forwarder-secret
              key: MQTT_USERNAME
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ttn-zabbix-mqtt-forwarder-secret
              key: MQTT_PASSWORD
